# Prog. Version..: '5.30.06-13.03.12(00000)'     #
#
#-------------------------------------------------------------------------------
# File: aws_efgw.4gl
# GENERATED BY fglwsdl build-587.103
#-------------------------------------------------------------------------------
# Service: EF2KGateWay
# Port:    EF2KGateWaySoap
# Server:  http://10.40.30.103/EF2KGateWay/EFService.asmx
#-------------------------------------------------------------------------------
# THIS FILE WAS GENERATED. DO NOT MODIFY.
#-------------------------------------------------------------------------------
#FUN-760054
# Modify.........: No.FUN-880046 08/08/12 by Echo Genero 2.11 調整
 
IMPORT com
IMPORT xml
 
 
#DATABASE ds  #FUN-760054 #FUN-880046
 
GLOBALS "../4gl/aws_efgw.inc"
 
#-------------------------------------------------------------------------------
DEFINE TipTopCoordinatorHTTPReq     com.HTTPRequest
DEFINE TipTopCoordinatorHTTPResp    com.HTTPResponse
 
#-------------------------------------------------------------------------------
 
#
# Operation: EFGateWay_TipTopCoordinator
#
 
#
# FUNCTION: EFGateWay_TipTopCoordinator
#
FUNCTION EFGateWay_TipTopCoordinator(p_strXMLInput)
  DEFINE	soapStatus		INTEGER
  DEFINE	p_strXMLInput		STRING
 
  LET EFGateWay_TipTopCoordinator.strXMLInput = p_strXMLInput
 
  LET soapStatus = EFGateWay_TipTopCoordinator_g()
 
  RETURN soapStatus, EFGateWay_TipTopCoordinatorResponse.Result
END FUNCTION
 
#
# FUNCTION: EFGateWay_TipTopCoordinator_g
#   RETURNING: soapStatus
#   INPUT: GLOBAL EFGateWay_TipTopCoordinator
#   OUTPUT: GLOBAL EFGateWay_TipTopCoordinatorResponse
#
FUNCTION EFGateWay_TipTopCoordinator_g()
  DEFINE wsstatus   INTEGER
  DEFINE retryAuth  INTEGER
  DEFINE retryProxy INTEGER
  DEFINE retry      INTEGER
  DEFINE request    com.HTTPRequest
  DEFINE response   com.HTTPResponse
  DEFINE writer     xml.DomDocument
  DEFINE reader     xml.DomDocument
  DEFINE envelope   xml.DomNode
  DEFINE header     xml.DomNode
  DEFINE body       xml.DomNode
  DEFINE node       xml.DomNode
 
  #
  # INIT VARIABLES
  #
  LET wsstatus = -1
  LET retryAuth = FALSE
  LET retryProxy = FALSE
  LET retry = TRUE
 
  IF EFGateWay_soapServerLocation IS NULL THEN
    LET EFGateWay_soapServerLocation = "http://10.40.30.103/EF2KGateWay/EFService.asmx"
  END IF
 
  #
  # CREATE REQUEST
  #
  TRY
    LET request = com.HTTPRequest.Create(EFGateWay_soapServerLocation)
    CALL request.setMethod("POST")
    CALL request.setCharset("UTF-8")
    CALL request.setHeader("SOAPAction","\"http://tempuri.org/EF2KGateWay/action/Entry.TipTopCoordinator\"")
  CATCH
    LET wsstatus = STATUS
    CALL WSHelper_FillSOAP11WSError("Client","Cannot create HTTPRequest")
    RETURN wsstatus
  END TRY
 
  # START LOOP
  WHILE retry
    LET retry = FALSE
 
    #
    # DOM Request
    #
 
    TRY
      # Building SOAP1.1 envelope
      LET writer = xml.DomDocument.Create()
      LET envelope = WSHelper_BuildSOAP11Envelope(writer)
      CALL writer.appendDocumentNode(envelope)
      LET body = WSHelper_BuildSOAP11Body(writer)
      CALL envelope.appendChild(body)
      CALL xml.Serializer.VariableToSoapSection5(EFGateWay_TipTopCoordinator,body)
 
      # Send SOAP envelope
      CALL request.doXmlRequest(writer)
    CATCH
      LET wsstatus = STATUS
      CALL WSHelper_FillSOAP11WSError("Client",SQLCA.SQLERRM)
      RETURN wsstatus
    END TRY
 
    #
    # PROCESS RESPONSE
    #
    TRY
      LET response = request.getResponse()
 
      CASE response.getStatusCode()
 
        WHEN 500 # SOAP Fault
          #
          # DOM SOAP FAULT
          #
          LET reader = response.getXmlResponse()
          LET envelope = WSHelper_RetrieveSOAP11Envelope(reader)
          IF envelope IS NULL THEN
            EXIT CASE
          END IF
          LET header = WSHelper_CheckSOAP11Header(envelope)
          LET body = WSHelper_RetrieveSOAP11Body(envelope,header)
          IF body IS NULL THEN
            EXIT CASE
          END IF
          CALL WSHelper_CheckSOAP11Fault(body.getFirstChildElement())
 
        WHEN 200 # SOAP Result
          #
          # DOM SOAP RESPONSE
          #
          LET reader = response.getXmlResponse()
          LET envelope = WSHelper_RetrieveSOAP11Envelope(reader)
          IF envelope IS NULL THEN
            EXIT CASE
          END IF
          # Skip headers
          LET header = WSHelper_CheckSOAP11Header(envelope)
          LET body = WSHelper_RetrieveSOAP11Body(envelope,header)
          IF body IS NOT NULL THEN
            # Check message
            LET node = WSHelper_RetrieveSOAP11Message(body)
            IF node IS NOT NULL THEN
              CALL Xml.Serializer.SoapSection5ToVariable(node,EFGateWay_TipTopCoordinatorResponse)
              LET wsstatus = 0
            END IF
          END IF
 
        WHEN 401 # HTTP Authentication
          IF retryAuth THEN
            CALL WSHelper_FillSOAP11WSError("Server","HTTP Error 401 ("||response.getStatusDescription()||")")
          ELSE
            LET retryAuth = TRUE
            LET retry = TRUE
          END IF
 
        WHEN 407 # Proxy Authentication
          IF retryProxy THEN
            CALL WSHelper_FillSOAP11WSError("Server","HTTP Error 407 ("||response.getStatusDescription()||")")
          ELSE
            LET retryProxy = TRUE
            LET retry = TRUE
          END IF
 
        OTHERWISE
          CALL WSHelper_FillSOAP11WSError("Server","HTTP Error "||response.getStatusCode()||" ("||response.getStatusDescription()||")")
 
      END CASE
    CATCH
      LET wsstatus = status
      CALL WSHelper_FillSOAP11WSError("Server",SQLCA.SQLERRM)
      RETURN wsstatus
    END TRY
 
  # END LOOP
  END WHILE
 
  RETURN wsstatus
 
END FUNCTION
 
 
FUNCTION EFGateWay_TipTopCoordinatorRequest_g()
  DEFINE wsstatus   INTEGER
  DEFINE writer     xml.DomDocument
  DEFINE envelope   xml.DomNode
  DEFINE header     xml.DomNode
  DEFINE body       xml.DomNode
  DEFINE node       xml.DomNode
 
  #
  # CHECK PREVIOUS CALL  
  #
  IF TipTopCoordinatorHTTPReq IS NOT NULL AND TipTopCoordinatorHTTPResp IS NULL THEN
    # Request was sent but there was no response yet
    CALL WSHelper_FillSOAP11WSError("Client","Cannot issue a new request until previous response was received")
    RETURN -2 # waiting for the response
  ELSE
    IF EFGateWay_soapServerLocation IS NULL THEN
      LET EFGateWay_soapServerLocation = "http://10.40.30.103/EF2KGateWay/EFService.asmx"
    END IF
  END IF
 
  #
  # CREATE REQUEST
  #
  TRY
    LET TipTopCoordinatorHTTPReq = com.HTTPRequest.Create(EFGateWay_soapServerLocation)
    CALL TipTopCoordinatorHTTPReq.setMethod("POST")
    CALL TipTopCoordinatorHTTPReq.setCharset("UTF-8")
    CALL TipTopCoordinatorHTTPReq.setHeader("SOAPAction","\"http://tempuri.org/EF2KGateWay/action/Entry.TipTopCoordinator\"")
  CATCH
    LET wsstatus = STATUS
    CALL WSHelper_FillSOAP11WSError("Client","Cannot create HTTPRequest")
    LET TipTopCoordinatorHTTPReq = NULL
    RETURN wsstatus
  END TRY
 
    #
    # DOM Request
    #
 
    TRY
      # Building SOAP1.1 envelope
      LET writer = xml.DomDocument.Create()
      LET envelope = WSHelper_BuildSOAP11Envelope(writer)
      CALL writer.appendDocumentNode(envelope)
      LET body = WSHelper_BuildSOAP11Body(writer)
      CALL envelope.appendChild(body)
      CALL xml.Serializer.VariableToSoapSection5(EFGateWay_TipTopCoordinator,body)
 
      # Send SOAP envelope
      CALL TipTopCoordinatorHTTPReq.doXmlRequest(writer)
    CATCH
      LET wsstatus = STATUS
      CALL WSHelper_FillSOAP11WSError("Client",SQLCA.SQLERRM)
      LET TipTopCoordinatorHTTPReq = NULL
      RETURN wsstatus
    END TRY
 
  #
  # PROCESS RESPONSE
  #
  TRY
    LET TipTopCoordinatorHTTPResp = TipTopCoordinatorHTTPReq.getAsyncResponse()
    RETURN 0 # SUCCESS
  CATCH
    LET wsstatus = STATUS
    CALL WSHelper_FillSOAP11WSError("Server",SQLCA.SQLERRM)
    LET TipTopCoordinatorHTTPReq = NULL
    RETURN wsstatus
  END TRY
END FUNCTION
 
 
FUNCTION EFGateWay_TipTopCoordinatorResponse_g()
  DEFINE wsstatus   INTEGER
  DEFINE reader     xml.DomDocument
  DEFINE envelope   xml.DomNode
  DEFINE header     xml.DomNode
  DEFINE body       xml.DomNode
  DEFINE node       xml.DomNode
 
  LET wsstatus = -1
 
  #
  # CHECK PREVIOUS CALL  
  #
  IF TipTopCoordinatorHTTPReq IS NULL THEN
    # No request was sent
    CALL WSHelper_FillSOAP11WSError("Client","No request has been sent")
    RETURN -1
  END IF
 
  TRY
    #
    # PROCESS RESPONSE
    #
    IF TipTopCoordinatorHTTPResp IS NULL THEN
      # Still no response, try again
      LET TipTopCoordinatorHTTPResp = TipTopCoordinatorHTTPReq.getAsyncResponse()
    END IF
 
    IF TipTopCoordinatorHTTPResp IS NULL THEN
      # We got no response, still waiting for
      CALL WSHelper_FillSOAP11WSError("Client","Response was not yet received")
      RETURN -2
    END IF
 
      CASE TipTopCoordinatorHTTPResp.getStatusCode()
 
        WHEN 500 # SOAP Fault
          #
          # DOM SOAP FAULT
          #
          LET reader = TipTopCoordinatorHTTPResp.getXmlResponse()
          LET envelope = WSHelper_RetrieveSOAP11Envelope(reader)
          IF envelope IS NULL THEN
            EXIT CASE
          END IF
          LET header = WSHelper_CheckSOAP11Header(envelope)
          LET body = WSHelper_RetrieveSOAP11Body(envelope,header)
          IF body IS NULL THEN
            EXIT CASE
          END IF
          CALL WSHelper_CheckSOAP11Fault(body.getFirstChildElement())
 
        WHEN 200 # SOAP Result
          #
          # DOM SOAP RESPONSE
          #
          LET reader = TipTopCoordinatorHTTPResp.getXmlResponse()
          LET envelope = WSHelper_RetrieveSOAP11Envelope(reader)
          IF envelope IS NULL THEN
            EXIT CASE
          END IF
          # Skip headers
          LET header = WSHelper_CheckSOAP11Header(envelope)
          LET body = WSHelper_RetrieveSOAP11Body(envelope,header)
          IF body IS NOT NULL THEN
            # Check message
            LET node = WSHelper_RetrieveSOAP11Message(body)
            IF node IS NOT NULL THEN
              CALL Xml.Serializer.SoapSection5ToVariable(node,EFGateWay_TipTopCoordinatorResponse)
              LET wsstatus = 0
            END IF
          END IF
 
        OTHERWISE
          CALL WSHelper_FillSOAP11WSError("Server","HTTP Error "||TipTopCoordinatorHTTPResp.getStatusCode()||" ("||TipTopCoordinatorHTTPResp.getStatusDescription()||")")
 
      END CASE
    CATCH
      LET wsstatus = status
      CALL WSHelper_FillSOAP11WSError("Server",SQLCA.SQLERRM)
    END TRY
 
  #
  # RESET VARIABLES
  #
  LET TipTopCoordinatorHTTPReq = NULL
  LET TipTopCoordinatorHTTPResp = NULL
  RETURN wsstatus
END FUNCTION
 
 
